# 建立'计算图'

In [5]:
#建立‘计算图’
import tensorflow as tf
x=tf.constant(2,name='x')#建立常量，有点像C
y=tf.Variable(x+5,name='y')#建立变量

In [6]:
#执行‘计算图’
with tf.Session() as sess:
    init=tf.global_variables_initializer()#初始化global变量
    sess.run(init)
    print('x=',sess.run(x))
    print('y=',sess.run(y))

x= 2
y= 7


In [8]:
x

<tf.Tensor 'x:0' shape=() dtype=int32>

# tensorflow placeholder
> 正如这个名字一样，hold on,hold on,告诉计算机等等在把值传给你，嘻嘻嘻嘻

In [13]:
a=tf.placeholder('int32')
b=tf.placeholder('int32')
c=tf.multiply(a,b)
with tf.Session() as sess:
    init=tf.global_variables_initializer()
    sess.run(init)
    print('c=',sess.run(c,feed_dict={a:6,b:7}))

c= 42


##### tensorflow数值运算常用的方法

- tf.add(x,y)
- tf.subtract(x,y)#减法
- tf.multiply(x,y)
- tf.divide(x,y)
- tf.mod(x,y)#余数
- tf.sqrt(x,name=None)
- tf.abs(x,name=None)

# tensorboard
> 正如其名，可视化已经建立的计算图

In [14]:
#承接上面的session
#下面代码将显示在tensorboard的数据写在log文件中
tf.summary.merge_all()#将显示在board的数据整合
train_writer=tf.summary.FileWriter('log/c',sess.graph)#写入log文件中

##### 启动tensorboard的方法
- activate tensorflow(虚拟环境名称)
- tensorboard --logdir=c:\python\log\c
- 用浏览器打开http://lacalhost:6006/

# 建立一维与二维张量

##### 建立一维张量

In [17]:
ts_x=tf.Variable([0.4,0.2,0.4])
with tf.Session() as sess:
    init=tf.global_variables_initializer()
    sess.run(init)
    x=sess.run(ts_x)
    print(x)

[0.4 0.2 0.4]


In [18]:
x.shape

(3,)

##### 建立二维张量

In [19]:
ts_x=tf.Variable([[0.4,0.2,0.4]])
with tf.Session() as sess:
    init=tf.global_variables_initializer()
    sess.run(init)
    x=sess.run(ts_x)
    print(x)

[[0.4 0.2 0.4]]


In [20]:
x.shape

(1, 3)

##### 建立新的二维张量

In [22]:
ts_x=tf.Variable([[0.4,0.2],
                 [0.3,0.4],
                 [-0.5,0.2]])
with tf.Session() as sess:
    init=tf.global_variables_initializer()
    sess.run(init)
    x=sess.run(ts_x)
    print(x)

[[ 0.4  0.2]
 [ 0.3  0.4]
 [-0.5  0.2]]


In [23]:
x.shape

(3, 2)

# 矩阵的基本运算

##### 矩阵的加法

In [25]:
x=tf.Variable([[1.,1.,1.]])
w=tf.Variable([[-0.1,-0.2],
              [-0.3,0.4],
              [0.5,0.6]])
xw=tf.matmul(x,w)

with tf.Session() as sess:
    init=tf.global_variables_initializer()
    sess.run(init)
    print(sess.run(xw))

[[0.09999999 0.8       ]]


##### 矩阵乘法与加法

In [26]:
x=tf.Variable([[1.,1.,1.]])
w=tf.Variable([[-0.1,-0.2],
              [-0.3,0.4],
              [0.5,0.6]])
b=tf.Variable([[0.1,0.2]])
xwb=tf.matmul(x,w)+b

with tf.Session() as sess:
    init=tf.global_variables_initializer()
    sess.run(init)
    print(sess.run(xwb))

[[0.19999999 1.        ]]
